- hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Run kong diff tasks
      include_role:
        name: kong
        tasks_from: deck_diff
  vars_files:
    - ../../group_vars/prod.yml
