- name: Fetch SSM parameter containing kong secrets
  become: false
  vars:
    _ssm_cmd: >
      aws secretsmanager get-secret-value --region '{{ aws_region }}' --secret-id '{{ aws_secret_id }}' --query SecretString --output text
  command: "{{ _ssm_cmd }}"
  register: secrets_params
  failed_when: secrets_params.rc != 0
  changed_when: false
  run_once: true
  delegate_to: localhost

- name: Parse secrets JSON from SSM parameter - local
  set_fact:
    kong_secrets_map: "{{ (secrets_params.stdout | default('') ) | from_json }}"
  failed_when: kong_secrets_map is not defined
  when: secrets_params.stdout is defined and secrets_params.stdout | length > 0
  run_once: true
  delegate_to: localhost

- name: Replace placeholders in kong files with secrets
  replace:
    path: "{{ item.0 }}"
    regexp: "{{ item.1.key }}"
    replace: "{{ item.1.value }}"
  loop: "{{ kong_temp_files | product(kong_secrets_map | dict2items) | list }}"
  no_log: true
  delegate_to: localhost
  when:
    - kong_temp_files is defined
    - kong_temp_files | length > 0
    - kong_secrets_map is defined
    - kong_secrets_map | length > 0