name: Update Airflow Values and Merge PR

on:
  workflow_call:
    inputs:
      dag_file:
        description: "Path to the DAG Python file that needs updating"
        required: true
        type: string
      dag_id:
        description: "Unique DAG identifier (used in image tag naming)"
        required: true
        type: string
      ecr_registry:
        description: "ECR registry URL where DAG images are stored"
        required: true
        type: string
      ecr_repository:
        description: "ECR repository URL where DAG images are stored"
        required: true
        type: string
      context:
        description: "Directory path to the Airflow DAGs folder"
        required: true
        type: string
      environment:
        description: "Environment for the PR (e.g., dev, staging, prod)"
        required: true
        type: string
      commit_id:
        description: "Commit ID to be used in the PR title"
        required: true
        type: string
      assest_repo:
        required: true
        type: string # Format: org/repo
      runner_label:
        required: false
        type: string
        default: ubuntu-latest
      auto_approve:
        description: "Automatically approve and merge the PR (true/false)"
        required: false
        type: boolean
        default: true

    secrets:
      GH_ID:
        required: false
      GH_TOKEN:
        required: false
      APPROVED_GH_TOKEN:
        required: false
      APPROVED_GH_ID:
        required: false

jobs:
  airflow-cd:
    runs-on: ${{ inputs.runner_label }}
    permissions:
      contents: write # Required to push changes to the repository
      pull-requests: write # Required to create and manage pull requests
      id-token: write
    outputs:
      SHORT_COMMIT: ${{ steps.vars.outputs.short_commit }}
      IMAGE_TAG: ${{ steps.vars.outputs.image_tag }}
      SOURCE_BRANCH: ${{ steps.vars.outputs.source_branch }}
      TARGET_BRANCH: ${{ steps.vars.outputs.target_branch }}
      #### GIT CREDENTIALS
      GH_TOKEN: ${{ steps.extract.outputs.GH_TOKEN }}
      GH_ID: ${{ steps.extract.outputs.GH_ID }}
      APPROVED_GH_TOKEN: ${{ steps.extract.outputs.APPROVED_GH_TOKEN }}
      APPROVED_GH_ID: ${{ steps.extract.outputs.APPROVED_GH_ID }}
    steps:
      ### Prepare job to set up environment variables and credentials
      - name: Get variables
        id: vars
        run: |
          short_commit=$(echo '${{ inputs.commit_id }}' | cut -c1-7)

          echo "SHORT_COMMIT=$short_commit" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ inputs.dag_id }}-v$short_commit-${{ inputs.environment }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=${{ inputs.ecr_repository }}" >> $GITHUB_ENV
          echo "ECR_REGISTRY=${{ inputs.ecr_registry }}" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=feature/DVOP-000-ci-${{ inputs.dag_id }}-${{ inputs.environment }}-$short_commit" >> $GITHUB_ENV
          echo "TARGET_BRANCH=develop" >> $GITHUB_ENV

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: arn:aws:iam::123456789:role/global-github-actions-role
          aws-region: us-east-1

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get GitHub secrets from AWS Secrets Manager
        id: extract
        run: |
          secret_json=$(aws secretsmanager get-secret-value --secret-id github-action --query SecretString --output text --region us-east-1)

          echo "GH_TOKEN=$(echo $secret_json | jq -r .GH_TOKEN)" >> $GITHUB_ENV
          echo "GH_ID=$(echo $secret_json | jq -r .GH_ID)" >> $GITHUB_ENV
          echo "APPROVED_GH_TOKEN=$(echo $secret_json | jq -r .APPROVED_GH_TOKEN)" >> $GITHUB_ENV
          echo "APPROVED_GH_ID=$(echo $secret_json | jq -r .APPROVED_GH_ID)" >> $GITHUB_ENV

      ### Update Helm values and create PR
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.assest_repo }}
          ref: ${{ env.TARGET_BRANCH }} # target base branch
          token: ${{ env.GH_TOKEN }} # Use the token from the prepare job

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch and update values
        id: update_values
        run: |
          git checkout -b ${{ env.SOURCE_BRANCH }}

          echo "Updating values.yaml"
          # Example: Update image tag in values.yaml (replace this logic with your own needs)
          sed -i "s/tag: [^ ]*/tag: ${{ env.IMAGE_TAG }}/g" ${{ inputs.context }}/${{ inputs.dag_file }}

          sed -i -e "s|^DAG_IMAGE_TAG = .*|DAG_IMAGE_TAG = \"${{ env.IMAGE_TAG }}\"|" \
            -e "s|^ECR_REPOSITORY = .*|ECR_REPOSITORY = \"${{ env.ECR_REPOSITORY }}\"|" \
            -e "s|^ECR_REGISTRY = .*|ECR_REGISTRY = \"${{ env.ECR_REGISTRY }}\"|" \
            ${{ inputs.context }}/${{ inputs.dag_file }}


          echo "Updated image tag to ${image_tag} in values.yaml"
          echo "Committing changes to $source_branch"

          # Add and commit changes
          git add ${{ inputs.context }}/${{ inputs.dag_file }}
          git commit -m "DVOP-000: bump image tag to ${{ env.IMAGE_TAG }} for ${{ inputs.context }}in {{ inputs.dag_file }}"
          echo "Pushing changes to ${{ env.SOURCE_BRANCH }}"
          git push origin ${{ env.SOURCE_BRANCH }}
          echo "Pushed changes to ${{ env.SOURCE_BRANCH }}"

      - name: Create PR
        id: create_pr
        run: |
          pr_title="DVOP-000: CI - ${{ inputs.dag_id }} ${{ inputs.environment }} - Auto-generated PR"
          pr_body="This PR was automatically generated by the CI workflow to update the image tag"
          head="${{ env.SOURCE_BRANCH }}"
          base="${{ env.TARGET_BRANCH }}"
          cat > pr_payload.json <<EOF
          {
            "title": "$pr_title",
            "body": "$pr_body",
            "head": "${{ env.SOURCE_BRANCH }}",
            "base": "${{ env.TARGET_BRANCH }}"
          }
          EOF

          response=$(curl -s -X POST \
            -u ${{ env.GH_ID }}:${{ env.GH_TOKEN }} \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ inputs.assest_repo }}/pulls \
            -d @pr_payload.json
          )
          echo "PR_NUMBER=$(echo ${response} | jq -r .number)" >> $GITHUB_ENV
          echo "PR_URL=$(echo ${response} | jq -r .html_url)" >> $GITHUB_ENV
          echo "Created PR: ${{ env.PR_URL }}"

      - name: Add Label
        run: |
          curl -s -X POST \
            -u ${{ env.GH_ID }}:${{ env.GH_TOKEN }} \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ inputs.assest_repo }}/issues/${{ env.PR_NUMBER }}/labels \
            -d '{"labels":["argocd","auto-update"]}'

      - name: Approve PR
        if: ${{ inputs.auto_approve == true }}
        run: |
          curl -s -X POST \
            -u ${{ env.APPROVED_GH_ID }}:${{ env.APPROVED_GH_TOKEN }} \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ inputs.assest_repo }}/pulls/${{ env.PR_NUMBER }}/reviews \
            -d '{"event":"APPROVE"}'

      - name: Merge PR
        if: ${{ inputs.auto_approve == true }}
        run: |
          curl -s -X PUT \
            -u ${{ env.GH_ID }}:${{ env.GH_TOKEN }} \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ inputs.assest_repo }}/pulls/${{ env.PR_NUMBER }}/merge \
            -d '{"commit_title": "${{ inputs.pr_title }}", "merge_method": "squash"}'
