name: Nonprod - Kong Sync

on:
  push:
    branches: [develop]
    paths:
      - "kong-config/*/nonprod/**"
      - "ansible/group_vars/nonprod/**"
      - "ansible/group_vars/nonprod.yml"
      - "ansible/group_vars/nonprod.yaml"
      - "ansible/host_vars/*/nonprod/**"

env:
  AWS_REGION: ap-southeast-1
  AWS_ACCOUNT_ID: "533267093295"

jobs:
  kong-sync-nonprod:
    runs-on: k8s
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true # Ensures repo folder is reset

      # Set up AWS credentials
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/global-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kong deck
        run: |
          mkdir -p "$RUNNER_TEMP/deck"
          curl -sSL https://github.com/kong/deck/releases/download/v1.52.0/deck_1.52.0_linux_amd64.tar.gz -o "$RUNNER_TEMP/deck/deck.tar.gz"
          tar -zxf "$RUNNER_TEMP/deck/deck.tar.gz" -C "$RUNNER_TEMP/deck"
          chmod +x "$RUNNER_TEMP/deck/deck"
          echo "$RUNNER_TEMP/deck" >> $GITHUB_PATH

      - name: Run kong_sync.yaml playbook (nonprod)
        run: |
          cd ansible
          ansible-playbook playbook/nonprod/kong_sync.yaml

      - name: Cleanup deck
        if: always() # ensures cleanup runs even if previous step fails
        run: rm -rf "$RUNNER_TEMP/deck"
