name: Reusable ECR Docker Build

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      ecr_registry:
        required: true
        type: string
      service_name:
        required: true
        type: string
      dag_id:
        required: false
        type: string
        default: ""
      dockerfile_path:
        required: false
        type: string
        default: Dockerfile
      context:
        required: false
        type: string
        default: .
      commit_id:
        required: true
        type: string
      environment:
        required: true
        type: string
      env_type:
        required: false
        type: string
        default: runtime
        description: "runtime or buildtime"
      runner_label:
        required: false
        type: string
        default: ubuntu-latest
      skip_dir:
        required: false
        type: string
        default: ""
      secret_id:
        required: false
        type: string
        default: ""
      ecr_name:
        required: false
        type: string
        default: ""
      docker_push:
        required: false
        type: boolean
        default: true
      trivy_timeout:
        required: false
        type: string
        default: "5m"
      extra_build_args:
        description: "Additional Docker build arguments in JSON format"
        required: false
        type: string
        default: "{}"
      docker_target:
        required: false
        type: string
      trivy_self_host:
        required: false
        type: boolean
        default: false
      platform:
        required: false
        type: string
        default: "linux/amd64"
      project:
        required: false
        type: string
        default: "general"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:
  build_trivy_push:
    runs-on: ${{ inputs.runner_label }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set AWS Account ID
        id: set_account
        run: |
          if [[ "${{ inputs.environment }}" = "prod" && "${{ inputs.env_type }}" = "buildtime" ]]; then
            echo "ACCOUNT_ID=123456789" >> $GITHUB_ENV
          else
            echo "ACCOUNT_ID=123456789" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/global-github-actions-role
          aws-region: ${{ inputs.aws_region }}

      - name: Get GitHub secrets from AWS Secrets Manager
        run: |
          # Fetch secret JSON
          secret_json=$(aws secretsmanager get-secret-value --secret-id github-action --query SecretString --output text --region us-east-1)

          # Extract values
          JF_ACCESS_TOKEN=$(echo "$secret_json" | jq -r .SECURITY_JFROG_TOKEN)
          JF_URL=$(echo "$secret_json" | jq -r .JFROG_HOST_URL)

          # Mask the token in logs
          echo "::add-mask::$JF_ACCESS_TOKEN"

          # Export to GitHub environment for next steps
          echo "JF_ACCESS_TOKEN=$JF_ACCESS_TOKEN" >> $GITHUB_ENV
          echo "JF_URL=$JF_URL" >> $GITHUB_ENV

      # - uses: gitleaks/gitleaks-action@v2
      #   env:
      #     GITHUB_TOKEN: ${{ env.GH_TOKEN }}
      #     GITLEAKS_LICENSE: ${{ env.GITLEAKS_LICENSE}}
      #     GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false

      - name: Gitleaks Scan
        id: gitleaks-scan
        run: |
          set -e
          echo "Running gitleaks scan..."
          gitleaks detect --source . --redact -v --no-banner --no-color > gitleaks.txt 2>&1 || true
          NO_LEAKS=$(grep -c "no leaks found" gitleaks.txt || true)
          if [[ $NO_LEAKS -eq 0 ]]; then
            echo "leaks_found=true" >> $GITHUB_OUTPUT
            echo "report<<EOF" >> $GITHUB_OUTPUT
            cat gitleaks.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "leaks_found=false" >> $GITHUB_OUTPUT
            echo "report<<EOF" >> $GITHUB_OUTPUT
            echo "✅ No secrets found." >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

          echo "Gitleaks Scan Report:"
          cat gitleaks.txt

      - name: Comment Gitleaks Report on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Gitleaks Report
          message: |
            ```bash
            ${{ steps.gitleaks-scan.outputs.report }}
            ```

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ env.JF_URL }}
          JF_ACCESS_TOKEN: ${{ env.JF_ACCESS_TOKEN }}

      - name: Upload gitleaks report to Artifactory
        if: ${{ steps.gitleaks-scan.outputs.leaks_found == 'true' }}
        run: |
          TS=$(date +'%Y%m%d-%H%M%S')
          jfrog rt upload \
            gitleaks.txt \
            "devops-security/${{ inputs.project }}/${{ inputs.service_name }}/gitleaks_${TS}.txt"

      - name: Fail workflow if leaks found
        if: ${{ steps.gitleaks-scan.outputs.leaks_found == 'true' }}
        run: |
          echo "❌ Gitleaks found secrets!"
          exit 1

      # - name: Configure AWS credentials with OIDC
      #   uses: aws-actions/configure-aws-credentials@v5.1.1
      #   with:
      #     role-to-assume: arn:aws:iam::${{ inputs.environment == 'prod' && '123456789' || '123456789' }}:role/global-github-actions-role
      #     aws-region: ${{ inputs.aws_region }}

      # New step: Get secrets from AWS Secrets Manager if env_type is 'build_time'
      - name: Get Build-time Secrets from AWS Secrets Manager
        id: get_build_secrets # Assign an ID to reference outputs
        if: inputs.env_type == 'buildtime'
        run: |
          # Fetch the secret value
          if [ -n "${{ inputs.secret_id }}" ]; then
            SECRET_VALUE=$(aws secretsmanager get-secret-value \
              --secret-id "${{ inputs.secret_id }}" \
              --query SecretString \
              --output text \
              --region ${{ inputs.aws_region }})
          else
            SECRET_VALUE=$(aws secretsmanager get-secret-value \
              --secret-id ${{ inputs.environment }}/${{ inputs.service_name }}/secrets \
              --query SecretString \
              --output text \
              --region ${{ inputs.aws_region }})
          fi

          build_args=""
          if echo "$SECRET_VALUE" | jq -e 'map_values(type == "string")' > /dev/null; then
            # Mask each secret value in logs
            for val in $(echo "$SECRET_VALUE" | jq -r 'to_entries[] | .value'); do
              echo "::add-mask::$val"
            done
            
            # Build args from JSON
            build_args=$(echo "$SECRET_VALUE" | jq -r 'to_entries | map("--build-arg \(.key)=\(.value)") | join(" ")')
          else
            echo "Warning: Secrets Manager secret is not a flat JSON object."
            build_args="--build-arg SECRET_FROM_SM='$SECRET_VALUE'"
            echo "::add-mask::$SECRET_VALUE"
          fi

          # Save to GitHub env (masked values will appear as *** in logs)
          echo "BUILD_ARGS=$build_args" >> "$GITHUB_ENV"

      - name: Merge Extra Build Args (JSON input)
        id: merge_extra_args
        if: inputs.env_type == 'buildtime' && inputs.extra_build_args != '{}'
        run: |
          extra_json='${{ inputs.extra_build_args }}'

          # Validate JSON format
          if ! echo "$extra_json" | jq empty 2>/dev/null; then
            echo "Invalid JSON format for extra_build_args"
            exit 1
          fi

          # Convert JSON to Docker build args
          extra_args=$(echo "$extra_json" | jq -r 'to_entries | map("--build-arg \(.key)=\(.value)") | join(" ")')

          # Merge with any previous BUILD_ARGS
          echo "BUILD_ARGS=${BUILD_ARGS:-} $extra_args" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
      #          buildkitd-flags: --allow-insecure-entitlement network.host
      #          network: host

      - name: Build Docker Image
        run: |
          short_commit=$(echo "${{ inputs.commit_id }}" | cut -c1-7)

          if [ -n "${{ inputs.dag_id }}" ]; then
            image_tag="${{ inputs.dag_id }}-v${short_commit}-${{ inputs.environment }}"
          else
            image_tag="v${short_commit}-${{ inputs.environment }}"
          fi

          echo "image_tag=$image_tag" >> $GITHUB_ENV
          echo "🔧 Building image with tag: $image_tag"

          if [ -n "${{ inputs.ecr_name }}" ]; then
            ECR_URI=${{ inputs.ecr_registry }}/${{ inputs.ecr_name }}
          else
            ECR_URI=${{ inputs.ecr_registry }}/${{ inputs.service_name }}
          fi

          echo "ECR_URI=$ECR_URI" >> $GITHUB_ENV

          if [ -n "${{ inputs.docker_target }}" ]; then
            TARGET_ARG="--target ${{ inputs.docker_target }}"
          else
            TARGET_ARG=""
          fi

          docker buildx build \
            --no-cache \
            --platform="${{ inputs.platform }}" \
            -f ${{ inputs.dockerfile_path }} \
            -t $ECR_URI:$image_tag \
            $TARGET_ARG \
            ${{ env.BUILD_ARGS }} \
            ${{ inputs.context }} \
            --load

      - name: Run Trivy vulnerability scanner in Trivy self host
        if: ${{ inputs.trivy_self_host }}
        id: trivy_self
        run: |
          export TRIVY_SERVER="https://nonprod-common-trivy.qualgo.dev"
          echo "Trivy Server: $TRIVY_SERVER"
              # Run scan
          trivy image \
            --format table \
            --output trivy.txt \
            --ignore-unfixed \
            --vuln-type os,library \
            --severity CRITICAL,HIGH \
            --skip-dirs ${{ inputs.skip_dir }} \
            --timeout ${{ inputs.trivy_timeout }} \
            ${{ env.ECR_URI }}:${{ env.image_tag }} || true

      # Run Trivy
      - name: Run Trivy vulnerability scanner
        if: ${{ inputs.trivy_self_host == false }}
        id: trivy_action
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: "${{ env.ECR_URI }}:${{ env.image_tag }}"
          format: "table"
          exit-code: "1"
          output: "trivy.txt"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          skip-dirs: ${{ inputs.skip_dir }}
          timeout: ${{ inputs.trivy_timeout }}
        env:
          TRIVY_DISABLE_VEX_NOTICE: true
        continue-on-error: true # Important: prevents workflow from stopping

      - name: Upload Trivy report to JFrog
        if: steps.trivy_action.outcome == 'failure' || steps.trivy_self.outcome == 'failure'
        run: |
          cat trivy.txt
          TS=$(date +'%Y%m%d-%H%M%S')
          jfrog rt upload \
            trivy.txt \
            "devops-security/${{ inputs.project }}/${{ inputs.service_name }}/trivy_${TS}.txt"
          exit 1

      - name: Login to Amazon ECR and Push Image
        if: ${{ inputs.docker_push }}
        run: |
          aws ecr get-login-password --region ${{ inputs.aws_region }} \
            | docker login --username AWS --password-stdin ${{ inputs.ecr_registry }}

          docker push ${{ env.ECR_URI }}:${{ env.image_tag }}
