name: TFSec Scan

on:
  workflow_call:
    inputs:
      working_directory:
        required: false
        type: string
        default: "."
      aws_region:
        required: false
        type: string
        default: "ap-southeast-1"

jobs:
  tfsec:
    name: Run tfsec
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
      
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ inputs.working_directory }}
