name: Reusable SDK for build and push android package

on:
  workflow_call:
    inputs:
      commit_id:
        required: true
        type: string
      runner_label:
        required: false
        type: string
        default: ubuntu-latest
      android_ndk_version:
        description: "NDK (Android Native Development Kit) Version"
        required: false
        type: string
        default: "r26d"
      kotlin_bindgen_bin_folder:
        description: "Kotlin bindings bin folder"
        required: false
        type: string
        default: "uniffi_bindgen"
      project:
        description: "Project Directory to build android package"
        required: true
        type: string
        default: ""
      rust_tool_chain:
        description: "Rust toolchain version: stable, nightly, beta"
        required: false
        type: string
        default: stable
      rust_tool_chain_target:
        description: "Target triple to install for rust toolchain"
        required: false
        type: string
        default: aarch64-linux-android, armv7-linux-androideabi, x86_64-linux-android
      android_abi:
        description: "A list of platform for building library"
        required: false
        type: string
        default: '[""]'
      aws_region:
        required: false
        type: string
        default: "ap-southeast-1"
      android_studio_template_repo:
        required: true
        type: string # Format: org/repo
      package_name:
        required: true
        type: string # For example: net.qualgo.apptracking
      repository_key:
        required: true
        type: string
      artifact_id:
        required: true
        type: string
      artifact_version:
        required: true
        type: string

jobs:
  build_android_packages:
    runs-on: ${{ inputs.runner_label }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: arn:aws:iam::123456789:role/global-github-actions-role
          aws-region: ${{ inputs.aws_region }}

      - name: Get GitHub secrets from AWS Secrets Manager
        id: extract
        run: |
          secret_json=$(aws secretsmanager get-secret-value --secret-id github-action --query SecretString --output text --region us-east-1)

          # Extracting the values
          SDK_USER_NAME=$(echo $secret_json | jq -r .SDK_USER_NAME)
          SDK_PROJECT_TOKEN=$(echo $secret_json | jq -r .SDK_PROJECT_TOKEN)
          JFROG_HOST_URL=$(echo $secret_json | jq -r .JFROG_HOST_URL)
          GH_TOKEN=$(echo $secret_json | jq -r .GH_TOKEN)

          # Mask the sensitive values
          echo "::add-mask::$SDK_USER_NAME"
          echo "::add-mask::$SDK_PROJECT_TOKEN"
          echo "::add-mask::$JFROG_HOST_URL"
          echo "::add-mask::$GH_TOKEN"

          # Save to GitHub environment
          echo "SDK_USER_NAME=$SDK_USER_NAME" >> $GITHUB_ENV
          echo "SDK_PROJECT_TOKEN=$SDK_PROJECT_TOKEN" >> $GITHUB_ENV
          echo "JFROG_HOST_URL=$JFROG_HOST_URL" >> $GITHUB_ENV
          echo "GH_TOKEN=$GH_TOKEN" >> $GITHUB_ENV
          echo "TARGET_BRANCH=develop" >> $GITHUB_ENV

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Required Dependencies
        id: install_required_dependencies
        run: |
          apt update -y
          apt install -y curl build-essential wget unzip apt-transport-https tree

      - name: Install the Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Cargo NDK
        id: install_cargo_ndk
        run: |
          cargo install --git https://github.com/bbqsrc/cargo-ndk.git --rev 9672f442e3524139f3369720cd8d83c8f29b7303 cargo-ndk

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ inputs.android_ndk_version }}
          add-to-path: true

      - name: Set NDK Environment Variable
        run: echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV

      - name: Clean build artifacts
        run: cargo clean

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ inputs.rust_tool_chain }}
          target: ${{ inputs.rust_tool_chain_target }}

      - name: Build Android packages (jniLibs)
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          # Define output dir
          ANDROID_DIR="$RUNNER_TEMP/android"

          # Get the android_abi (for eg. armeabi-v7a)
          input_string=$(echo ${{ inputs.android_abi }})

          # Remove brackets and split into an array
          input_string=${input_string//[\[\]]/}
          IFS=', ' read -r -a PLATFORM <<< "$input_string"  # Split into array

          targets=$(printf " -t %s" "${PLATFORM[@]}")

          # Build with cargo-ndk for all targets
          cd ./crates/${{ inputs.project }}
          cargo ndk \
            $targets \
            -o "$ANDROID_DIR/jniLibs" \
            build --release

          jnilibs_path="$ANDROID_DIR/jniLibs/"
          echo "jnilibs_path=$jnilibs_path" >> $GITHUB_ENV

      - name: Build Android packages (bindings)
        run: |
          # Define output dir
          ANDROID_DIR="$RUNNER_TEMP/android"
          # Specify the directory to search file .so
          directory="$ANDROID_DIR/jniLibs"
          file_pattern="lib*.so"

          # Find the file and save its name to a variable
          file_name=$(find "$directory" -type f -name "$file_pattern" -print -quit)
          if [ -n "$file_name" ]; then
            echo "Found file: $file_name"
          else
            echo "No .so file found"
            exit 1
          fi

          # Generate Kotlin bindings
          output_bindings="$ANDROID_DIR/bindings"
          cargo run --bin ${{ inputs.kotlin_bindgen_bin_folder }} generate \
            --library "$file_name" \
            --language kotlin \
            --out-dir "$output_bindings" \
            --no-format

          echo "bindings_path=$output_bindings" >> $GITHUB_ENV

      # Checkout the template repository to build .aar file
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.android_studio_template_repo }}
          ref: ${{ env.TARGET_BRANCH }} # target base branch
          token: ${{ env.GH_TOKEN }} # Use the token from the prepare job

      - name: Update .so file and .kt file
        run: |
          # remove all template file: .so and jniLibs
          rm -rf mylibrary/src/main/java/net
          rm -rf mylibrary/src/main/jniLibs/*

          # Replace dots with slashes to create directory structure
          IFS='.' read -ra ADDR <<< "${{ inputs.package_name }}"
          mkdir -p "mylibrary/src/main/java/${ADDR[*]}"

          # Update .kt file
          ## Get the path of .kt file
          kt_file=$(find "${{ env.bindings_path }}" -type f -name "*.kt" -print -quit)
          ## Copy .kt file
          cp "$kt_file" "mylibrary/src/main/java/${ADDR[*]}"

          # Update jniLibs directory
          mkdir -p mylibrary/src/main/jniLibs
          cp -r ${{ env.jnilibs_path }}* mylibrary/src/main/jniLibs/

          # Update namespace in `
          # Set the path to the build.gradle file you want to update
          file_path="mylibrary/build.gradle"
          sed -i "s|namespace 'net.qualgo.mylibrary'|namespace '${{ inputs.package_name }}'|g" "$file_path"
          echo "Updated namespace in $file_path."

      - name: Update release info
        run: |
          file_path="mylibrary/build.gradle"
          sed -i "s|<artifactory-url>|${{ env.JFROG_HOST_URL }}|g" "$file_path"
          sed -i "s|<artifact-id>|${{ inputs.artifact_id }}|g" "$file_path"
          sed -i "s|<artifact-version>|${{ inputs.artifact_version }}|g" "$file_path"
          sed -i "s|<repo-key>|${{ inputs.repository_key }}|g" "$file_path"
          sed -i "s|<username>|${{ env.SDK_USER_NAME }}|g" "$file_path"
          sed -i "s|<password>|${{ env.SDK_PROJECT_TOKEN }}|g" "$file_path"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Find and upload .aar file
        run: |
          # Find the file and save its name to a variable
            file_name=$(find . -type f -name "*release.aar" -print -quit)
            if [ -n "$file_name" ]; then
              echo "Found file: $file_name"
            else
              echo "No .aar file found"
              exit 1
            fi

          echo "aar_path=$file_name" >> $GITHUB_ENV

      - name: Upload android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-aar-artifacts
          path: |
            ${{ env.aar_path }}

      - name: Upload android artifacts to Jfrog artifactory
        run: ./gradlew artifactoryPublish
